### ISSUE TITLE
glCopyImageSubData used even if GL_ARB_copy_image is not available

### ISSUE THREAD

**Issue by Holzhaus** [virtual-programming/bioshockinfinite-linux#27]
Now that mesa finally supports OpenGL 4.1, #7 should no longer be an issue (at least on nvc0 hardware).

Unfortunately, it looks like Bioshock Infinite also needs [GL_ARB_copy_image](https://www.opengl.org/registry/specs/ARB/copy_image.txt) (which is part of OpenGL 4.3), but doesn't check if it's actually available:

> However the report is that on top of nouveau that (accurately) exposes GL 4.1 (i.e. has tess and subroutines merged in), it starts calling glCopyImageSubData without
ARB_copy_image having been exposed. Mesa naturally returns
INVALID_OPERATION, and nothing is drawn other than the cursor and
subtitles. My naive implementation (earlier in the thread) makes the
game operate properly.

See [this](http://lists.freedesktop.org/archives/mesa-dev/2015-July/089272.html) for details.

**Expected behaviour:** Check if GL_ARB_copy_image is available, and exit gracefully if it's not.

**Comment by imirkin** [comment]
I've pushed a hack GL_ARB_copy_image implementation to mesa (not enabled by default since it doesn't handle all the various cases). However experimentally it's good enough for Bioshock Infinite to run -- you can force-enable it with `MESA_EXTENSION_OVERRIDE=GL_ARB_copy_image`

However GL_ARB_copy_image functionality only becomes core in GL 4.3, and so the application must check for the extension string to be provided on when the reported GL version is below 4.3.

**Comment by vpltd-kgalaj** [comment]
We're using GLEW (slightly modified to use glGetStringi where available) to detect available OpenGL extensions. We're relying on GLEW_ARB_copy_image, which in source code is:

> GLEW_ARB_copy_image = GLEW_VERSION_4_3 || _glewSearchExtension("GL_ARB_copy_image", extStart, extEnd);

and we never call glCopyImageSubData without it, falling back to other solutions. Unfortunately I can't test with the driver to check what goes wrong, but the code is so simple that...

Well, I see that on Linux we also use glewExperimental = true, and that turns on the following line:

>  if (glewExperimental || GLEW_ARB_copy_image) GLEW_ARB_copy_image = !_glewInit_GL_ARB_copy_image(GLEW_CONTEXT_ARG_VAR_INIT);

where

> static GLboolean _glewInit_GL_ARB_copy_image (GLEW_CONTEXT_ARG_DEF_INIT)
> {
>  GLboolean r = GL_FALSE;
>
>  r = ((glCopyImageSubData = (PFNGLCOPYIMAGESUBDATAPROC)glewGetProcAddress((const GLubyte*)"glCopyImageSubData")) == NULL) || r;
>
>  return r;
> }

which would explain the problem, if MESA driver is exposing glCopyImageSubData export.

We have a command-line option to disable it: --eon_disable_arb_copy_image , which forces it off, even if GLEW_ARB_copy_image was on, but I'm not sure if it was already there when we released newest build of Bioshock Infinite.

**Comment by imirkin** [comment]
@vpltd-kgalaj GetProcAddress("glDoesNotExist") returns non-NULL as well. Just because it returns non-null doesn't mean that calling it will lead to anything other than INVALID_OPERATION... you must check the extension string (and/or version).

**Comment by vpltd-kgalaj** [comment]
Yes, I now removed glewExperimental, and the next experimental version won't have it. On the other hand, it was on for a reason - glGenVertexArrays() on AMD or NVidia was returning NULL with it off - so depending on tests I may have to work around it in another way. Standards are good, but in addition to them imo it's best not to return non-NULL when the call isn't actually operational.

**Comment by imirkin** [comment]
@vpltd-kgalaj OK great! Unfortunately it's not easy to determine what is operational. Different hardware operated by the same driver may have different features exposed. That information is not available to the glXGetProcAddressARB logic.

Perhaps you can encourage the game publishers you work with to have a program similar to Valve's (http://lists.freedesktop.org/archives/dri-devel/2015-April/081045.html) to give Mesa developers access to their games so that these issues can come out sooner rather than later. (I know this is the wrong forum for such a comment, but I don't know of a right forum.)

**Comment by Holzhaus** [comment]
@imirkin I see what you did there ;-)

**Comment by imirkin** [comment]
By the way, here's some more info on glXGetProcAddress(ARB), how it works, and (in part) why:

http://dri.freedesktop.org/wiki/glXGetProcAddressNeverReturnsNULL/

**Comment by vpltd-kgalaj** [comment]
Thanks for the information. I forwarded your suggestion higher up, so something might come out of this, considering that we usually work with NVidia, AMD and Intel teams once we have a Steam beta :) I guess some NDAs would be in order, but as a programmer, it seems a good thing to me to have more pairs of eyes look at interoperability of code and drivers. We'll see what they say.

**Comment by lordheavy** [comment]
it's now fixed with latest release and radeonsi/mesa drivers

**Comment by liamdawe** [comment]
Could others confirm it's fixed so this can be closed?

**Comment by Holzhaus** [comment]
I can confirm that Bioshock works correctly on my r600 APU using mesa drivers when starting it with `MESA_GL_VERSION_OVERRIDE=4.1 MESA_GLSL_VERSION_OVERRIDE=410 %command%`.

That override is needed, because OpenGL 4.1 core profile doesn't work yet (`GL_ARB_tessellation_shader` is still missing).

Considering that [`GL_ARB_copy_image` isn't implemented in mesa for r600 cards](http://mesamatrix.net/#Version_OpenGL4.3-GLSL4.30), this issue seems to be fixed.

```
Bioshock Infinite - Steam Content Build ID: 766387
APU: AMD A6-3410MX APU with Radeon(tm) HD Graphics (Radeon HD 6520G)
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD SUMO (DRM 2.43.0, LLVM 3.7.0)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.0.4
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL version string: 3.0 Mesa 11.0.4
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.0.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```

Full glxinfo output can be [found here](https://gist.github.com/Holzhaus/3de3555727ffbecb0580).
